name=2FATouchCore
version=1.0.0
author=Amauri Bueno dos Santos
maintainer=Amauri Bueno dos Santos
sentence=Biblioteca Core do 2FATouch para ESP32 CYD
paragraph=Contem todas as funcoes essenciais do 2FATouch: geracao de QR Code, animacoes do Creeper, exibicao climatica, TOTP, teclado touch e utilitarios.
category=Display
url=https://github.com/Annabel369/2FATouch
architectures=esp32
depends=TFT_eSPI, ESP32FtpServer, ArduinoJson, NTPClient, ESP32Servo, XPT2046_Touchscreen, TJpg_Decoder
